-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tbl_product
(
    pro_id bigserial NOT NULL,
    pro_description character varying(50) NOT NULL,
    pro_price numeric NOT NULL,
    PRIMARY KEY (pro_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_cart
(
    pro_id bigint NOT NULL,
    cart_quantity numeric NOT NULL
);

ALTER TABLE IF EXISTS public.tbl_cart
    ADD FOREIGN KEY (pro_id)
    REFERENCES public.tbl_product (pro_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;