-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tbl_my_contacts
(
    contact_id bigserial NOT NULL,
    last_name character varying(50) NOT NULL,
    first_name character varying(50) NOT NULL,
    phone character varying(15) NOT NULL,
    email character varying(50) NOT NULL,
    gender "char" NOT NULL CHECK(gender IN ('M', 'F')),
    birthday date NOT NULL,
    prof_id bigint NOT NULL,
    zip_code bigint NOT NULL,
    status_id bigint NOT NULL,
    PRIMARY KEY (contact_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_interests
(
    interest_id bigserial NOT NULL,
    con_interest character varying(50) NOT NULL,
    PRIMARY KEY (interest_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_seeking
(
    seeking_id bigserial NOT NULL,
    con_seeking character varying(50) NOT NULL,
    PRIMARY KEY (seeking_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_profession
(
    prof_id bigserial NOT NULL,
    con_profession character varying(50) NOT NULL UNIQUE,
    PRIMARY KEY (prof_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_zip_code
(
    zip_code_id bigserial NOT NULL,
    zip_code smallint NOT NULL CHECK(zip_code<9999),
    con_province character varying(50) NOT NULL,
    main_city character varying(50) NOT NULL,
    sub_city character varying(50) NOT NULL,
    PRIMARY KEY (zip_code_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_status
(
    status_id bigserial NOT NULL,
    con_status character varying(50) NOT NULL,
    PRIMARY KEY (status_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_my_contacts_interests
(
    tbl_my_contacts_contact_id bigint NOT NULL,
    tbl_interests_interest_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tbl_my_contacts_seeking
(
    tbl_my_contacts_contact_id bigint NOT NULL,
    tbl_seeking_seeking_id bigint NOT NULL
);

ALTER TABLE IF EXISTS public.tbl_my_contacts
    ADD FOREIGN KEY (prof_id)
    REFERENCES public.tbl_profession (prof_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbl_my_contacts
    ADD FOREIGN KEY (zip_code)
    REFERENCES public.tbl_zip_code (zip_code_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbl_my_contacts
    ADD FOREIGN KEY (status_id)
    REFERENCES public.tbl_status (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbl_my_contacts_interests
    ADD FOREIGN KEY (tbl_my_contacts_contact_id)
    REFERENCES public.tbl_my_contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbl_my_contacts_interests
    ADD FOREIGN KEY (tbl_interests_interest_id)
    REFERENCES public.tbl_interests (interest_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbl_my_contacts_seeking
    ADD FOREIGN KEY (tbl_my_contacts_contact_id)
    REFERENCES public.tbl_my_contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tbl_my_contacts_seeking
    ADD FOREIGN KEY (tbl_seeking_seeking_id)
    REFERENCES public.tbl_seeking (seeking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;